wandb_version: 1

dataset_dir:
  desc: null
  value: ./raw_data
save_dir:
  desc: null
  value: ./edge_grasp_net_pretrained_para
vn_save_dir:
  desc: null
  value: ./vn_edge_pretrained_para
load:
  desc: null
  value: 0
epoch:
  desc: null
  value: 200
sample_num:
  desc: null
  value: 5
test_interval:
  desc: null
  value: 1
save_interval:
  desc: null
  value: 10
verbose:
  desc: null
  value: true
train:
  desc: null
  value: true
vn:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683130081.054871
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.1
      8:
      - 5
